#!/usr/bin/env bash
# Daily re-export + publish. Re-exports every published announcement; commits
# each NEW / CHANGED / WITHDRAWN announcement individually with today's date and
# an honest message (content-changed vs metadata-only), refreshes the manifest,
# then pushes. This is what proves over time that announcements aren't silently
# modified: every change becomes a dated, public, diffable commit.
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO"
OWNER=cfi-co
GHREPO=awards
LOG=/var/log/awards-archive-sync.log
WP=/var/customers/webs/marten/cfi.co/awards
# Array, not a string: the values contain spaces and MUST NOT word-split.
# (A bare `git $ID` made git read "Awards" as a subcommand and aborted the
#  whole sync the first time there was anything to commit.)
ID=(-c user.name="CFI.co Awards Archive" -c user.email="awards-archive@cfi.co")

# Append once to the log. Do NOT also echo to stderr: cron already redirects
# stdout+stderr to $LOG, so a tee+>&2 doubled every line.
log() { printf '[%s] %s\n' "$(date -u +%FT%TZ)" "$*" >>"$LOG"; }

# Single-instance lock.
exec 9>/var/lock/awards-archive-sync.lock
flock -n 9 || { log "another sync running, skip"; exit 0; }

log "sync start"

# 0a. Dirty-tree guard (added 2026-07-30, at Anthony Michael's request). This
#     script regenerates the manifest over whatever is in the working tree and
#     signs it with the archive key - previously safe because only this script
#     ever changed that tree. It no longer is: reviewed content now arrives as
#     its own commit from outside this script (custodian/publisher signature
#     files, verify.sh fixes, and so on) BEFORE sync.sh runs. If the tree is
#     dirty at start, that content was never committed as its own reviewed
#     change - continuing would sign an untracked, unreviewed diff under the
#     archive's own key. Refuse outright rather than guess what it is.
if [ -n "$(git status --porcelain)" ]; then
  log "ABORT: working tree is dirty at sync start - refusing to sign unreviewed changes"
  git status --porcelain >>"$LOG"
  exit 1
fi

# 0. Refresh Wayback evidence: re-check non-archived URLs (cheap — archived ones
#    are skipped) and submit a bounded batch of any still-missing URLs. Best-effort.
php8.2 scripts/wayback.php check     >>"$LOG" 2>&1 || true
php8.2 scripts/wayback.php submit 25 >>"$LOG" 2>&1 || true

# 1. Re-export live data (overwrites announcements/; identical files = no diff).
php8.2 /usr/local/bin/wp eval-file scripts/export.php --allow-root --path="$WP" >/dev/null

git add -A announcements

mapfile -t CHANGED < <(git diff --cached --name-only -- announcements \
                       | sed -E 's/\.(md|json)$//' | sort -u)

if [ "${#CHANGED[@]}" -eq 0 ]; then
  log "no announcement changes"
else
  log "${#CHANGED[@]} announcement(s) changed"
  for stem in "${CHANGED[@]}"; do
    md="$stem.md"; js="$stem.json"
    year="$(basename "$(dirname "$stem")")"
    id="$(basename "$stem" | grep -oE '^[0-9]+')"

    if git cat-file -e "HEAD:$js" 2>/dev/null; then in_head=1; else in_head=0; fi
    if [ -f "$js" ]; then on_disk=1; else on_disk=0; fi

    if   [ $on_disk -eq 1 ] && [ $in_head -eq 0 ]; then
      title="$(php8.2 -r '$j=json_decode(file_get_contents($argv[1]),true);echo $j["title"];' "$js")"
      msg="Add award announcement #$id: $title ($year)"
    elif [ $on_disk -eq 0 ] && [ $in_head -eq 1 ]; then
      title="$(git show "HEAD:$js" | php8.2 -r '$j=json_decode(stream_get_contents(STDIN),true);echo $j["title"];')"
      msg="Withdraw award announcement #$id: $title ($year) — no longer published"
    else
      oldh="$(git show "HEAD:$js" | php8.2 -r '$j=json_decode(stream_get_contents(STDIN),true);echo $j["content_sha256"];')"
      newh="$(php8.2 -r '$j=json_decode(file_get_contents($argv[1]),true);echo $j["content_sha256"];' "$js")"
      title="$(php8.2 -r '$j=json_decode(file_get_contents($argv[1]),true);echo $j["title"];' "$js")"
      if [ "$oldh" != "$newh" ]; then
        msg="Update award announcement #$id: $title — CONTENT CHANGED"
      else
        msg="Update award announcement #$id: $title — metadata only (content unchanged)"
      fi
    fi
    git "${ID[@]}" commit -q --no-verify -m "$msg" -- "$md" "$js"
    log "  $msg"
  done
fi

# 1b. Refresh the root-level catalog index (index.jsonl is regenerated by
#     export.php alongside the records). It is a derived enumeration of the whole
#     corpus, so it is committed as one file, not per-announcement. On days with
#     no record change it is byte-identical and produces no commit. (The `if !`
#     guard keeps `set -e` happy when there IS a diff.)
git add index.jsonl
if ! git diff --cached --quiet -- index.jsonl; then
  git "${ID[@]}" commit -q --no-verify -m "Refresh announcement index ($(date -u +%F))"
  log "  index.jsonl refreshed"
fi

# 2. Refresh whole-tree manifest if anything moved. (Paths are newline-safe:
#    slugs are sanitised; -r avoids the empty-input -> hash-stdin trap.)
#    The manifest excludes itself AND its detached signature — both change as a
#    consequence of hashing, so neither can be inside the hash list (verify.sh
#    applies the identical exclusion).
git ls-files | grep -vxF -e 'MANIFEST.sha256' -e 'MANIFEST.sha256.asc' -e 'MANIFEST.sha256.ots' | xargs -r -d '\n' sha256sum > MANIFEST.sha256
if ! git diff --quiet -- MANIFEST.sha256 || [ ! -f MANIFEST.sha256.asc ]; then
  # Detached-sign the refreshed manifest (archive key 876FF2AA39133BF8; this
  # cron runs as root, whose keyring holds the key). Signing happens only when
  # the manifest actually changed, so quiet days stay commit-free.
  gpg --batch --yes --armor --detach-sign --local-user 876FF2AA39133BF8 \
      --output MANIFEST.sha256.asc MANIFEST.sha256
  git add MANIFEST.sha256 MANIFEST.sha256.asc
  git "${ID[@]}" commit -q --no-verify -m "Refresh + sign SHA-256 manifest ($(date -u +%F))"
fi

# 3. Push. (git push is a no-op if already up to date.)
APP_ENV="${AWARDS_APP_ENV:-/root/.config/awards-archive/app.env}"
APP_PEM="$(grep -E '^PEM=' "$APP_ENV" 2>/dev/null | cut -d= -f2-)"
if [ ! -r "$APP_ENV" ] || ! grep -qE '^APP_ID=[0-9]+' "$APP_ENV" \
   || [ -z "$APP_PEM" ] || [ ! -r "$APP_PEM" ]; then
  log "GitHub App not configured yet — local commits ready, push skipped"
  log "sync done"; exit 0
fi
TOKEN="$(php8.2 scripts/gh-app-token.php)" || { log "token mint FAILED"; exit 1; }
git push -q "https://x-access-token:${TOKEN}@github.com/${OWNER}/${GHREPO}.git" HEAD:main
log "pushed"
log "sync done"
